version: "3.9"
services:
  backend:
    container_name: fastapi-uvicorn-backend
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    command: |
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --reload --workers 3 --host 0.0.0.0 --port 8000'
    volumes:
      - ./services/backend/:/backend/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgresql://fastapi:fastapi@db/fastapi_dev
  db:
    image: postgres:14-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fastapi_dev
volumes:
  postgres_data:
    name: postgres_data