    ports:
      - 8002:8000

version: "3.9"
services:
  backend:
    container_name: fastapi-uvicorn-backend
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./services/backend/:/backend/
    ports:
      - 8002:8000
    env_file:
      - .local.env