"""Add subjects table

Revision ID: 088f30b41394
Revises: d348b2cfc619
Create Date: 2021-12-04 14:20:28.939362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088f30b41394'
down_revision = 'd348b2cfc619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_subjects_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjects')
    # ### end Alembic commands ###
