"""Fix types works

Revision ID: 340c59e2160c
Revises: 874db9c5a19d
Create Date: 2021-12-05 13:47:04.772395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340c59e2160c'
down_revision = '874db9c5a19d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works', 'headline',
                    type_=sa.String(),
                    nullable=False)
    op.alter_column('works', 'description',
                    type_=sa.String(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # WARING! Not downgradable
    # op.alter_column('works', 'headline',
    #                 type_=sa.DateTime(),
    #                 server_default='now()',
    #                 nullable=False)
    # op.alter_column('works', 'description',
    #                 type_=sa.DateTime(),
    #                 server_default='now()',
    #                 nullable=True)
    # ### end Alembic commands ###
