"""Default class value

Revision ID: 478b2015ee48
Revises: 6d48e2a022db
Create Date: 2021-12-12 12:26:14.817908

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '478b2015ee48'
down_revision = '6d48e2a022db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'number',
                    server_default=str(datetime.now().year))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'number',
                    server_default=False)
    # ### end Alembic commands ###
