"""Remove user unique constraint

Revision ID: 6d48e2a022db
Revises: 340c59e2160c
Create Date: 2021-12-07 21:57:03.326337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d48e2a022db'
down_revision = '340c59e2160c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_name_surname_midname_birthday', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_users_name_surname_midname_birthday', 'users', ['name', 'surname', 'midname', 'birthday'])
    # ### end Alembic commands ###
