"""Add marks table

Revision ID: 769871c38a82
Revises: c1569708f51c
Create Date: 2021-12-04 23:40:10.457064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769871c38a82'
down_revision = 'c1569708f51c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('workplace_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.user_id'], name='marks_student_id_fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workplace_id'], ['workplaces.id'], name='marks_workplace_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marks')
    # ### end Alembic commands ###
