"""Add classes table

Revision ID: 78f1b399bf40
Revises: 7aa7c721225f
Create Date: 2021-12-04 15:08:12.115360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f1b399bf40'
down_revision = '7aa7c721225f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True, comment='Belonging to the concrete class among the same year i.e. A, B, C etc.'),
    sa.Column('number', sa.Integer(), nullable=True, comment='The year the students went to first grade '),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'number', name='uq_classes_name_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classes')
    # ### end Alembic commands ###
