"""Fix mark-work FK

Revision ID: 874db9c5a19d
Revises: 45202422ac1b
Create Date: 2021-12-05 00:46:13.498777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874db9c5a19d'
down_revision = '45202422ac1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('work_id', sa.Integer(), nullable=False))
    op.drop_constraint('marks_workplace_id_fk', 'marks', type_='foreignkey')
    op.create_foreign_key('marks_work_id_fk', 'marks', 'works', ['work_id'], ['id'], ondelete='CASCADE')
    op.drop_column('marks', 'workplace_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('workplace_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('marks_work_id_fk', 'marks', type_='foreignkey')
    op.create_foreign_key('marks_workplace_id_fk', 'marks', 'workplaces', ['workplace_id'], ['id'], ondelete='CASCADE')
    op.drop_column('marks', 'work_id')
    # ### end Alembic commands ###
