"""Add teachers table

Revision ID: ce0dc62aeaeb
Revises: de78d6a7b21d
Create Date: 2021-12-03 00:40:22.263009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce0dc62aeaeb'
down_revision = 'de78d6a7b21d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='teachers_users_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('users_id', name='teachers_users_id_pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers')
    # ### end Alembic commands ###
