"""Add teachers table

Revision ID: d348b2cfc619
Revises: de78d6a7b21d
Create Date: 2021-12-04 13:18:57.806109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd348b2cfc619'
down_revision = 'de78d6a7b21d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='teachers_users_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name='teachers_users_id_pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers')
    # ### end Alembic commands ###
