"""Change scope type

Revision ID: de78d6a7b21d
Revises: b541214031b4
Create Date: 2021-11-28 23:14:27.951595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'de78d6a7b21d'
down_revision = 'b541214031b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=64), nullable=False))
    op.drop_column('users', 'password')
    op.drop_column('users', 'type')
    op.add_column('users', sa.Column('type', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'type')
    op.add_column('users', sa.Column('type', postgresql.ENUM('administration', 'teacher', 'student', name='usertype'), nullable=False))
    # ### end Alembic commands ###
