"""Rename work_type -> work_types table

Revision ID: e72c34f78ac2
Revises: 78f1b399bf40
Create Date: 2021-12-04 15:12:44.977899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e72c34f78ac2'
down_revision = '78f1b399bf40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_work_type_name')
    )
    op.drop_table('work_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_type',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('work_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='work_type_pkey'),
    sa.UniqueConstraint('work_type', name='uq_work_type')
    )
    op.drop_table('work_types')
    # ### end Alembic commands ###
